### ISSUE TITLE
Install on mac

### ISSUE THREAD

**Issue by PierreMarieRiviere** [netPark/node-openalpr#17]
I am sure this is linked to #1 but the problem persists. node-openalpr won't compile when pushing to Heroku

Here is my log:

```
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > node-openalpr@1.1.1 install /tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr
remote:        > node-pre-gyp install --build-from-source --fallback-to-build
remote:        
remote:        make: Entering directory `/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/build'
remote:        CXX(target) Release/obj.target/node_openalpr/src/node_openalpr.o
remote:        ../src/node_openalpr.cc: In function ‘char* get(v8::Local<v8::Value>)’:
remote:        ../src/node_openalpr.cc:133:9: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
remote:        return "";
remote:        ^
remote:        ../src/node_openalpr.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE IdentifyLicense(Nan::NAN_METHOD_ARGS_TYPE)’:
remote:        ../src/node_openalpr.cc:193:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
remote:        for (int i = 0; i < regionsArray->Length (); i++) {
remote:        ^
remote:        SOLINK_MODULE(target) Release/obj.target/node_openalpr.node
remote:        g++: error: /usr/lib/libopenalpr.so: No such file or directory
remote:        make: *** [Release/obj.target/node_openalpr.node] Error 1
remote:        make: Leaving directory `/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
remote:        gyp ERR! stack     at emitTwo (events.js:106:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
remote:        gyp ERR! System Linux 3.13.0-105-generic
remote:        gyp ERR! command "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.heroku/node/bin/node" "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--fallback-to-build" "--module=/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/release/linux_x64/node_openalpr.node" "--module_name=node_openalpr" "--module_path=/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/release/linux_x64"
remote:        gyp ERR! cwd /tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr
remote:        gyp ERR! node -v v6.9.1
remote:        gyp ERR! node-gyp -v v3.4.0
remote:        gyp ERR! not ok
remote:        node-pre-gyp ERR! build error
remote:        node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.heroku/node/bin/node /tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --fallback-to-build --module=/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/release/linux_x64/node_openalpr.node --module_name=node_openalpr --module_path=/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/release/linux_x64' (1)
remote:        node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
remote:        node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
remote:        node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
remote:        node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
remote:        node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        node-pre-gyp ERR! System Linux 3.13.0-105-generic
remote:        node-pre-gyp ERR! command "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.heroku/node/bin/node" "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/.bin/node-pre-gyp" "install" "--build-from-source" "--fallback-to-build"
remote:        node-pre-gyp ERR! cwd /tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr
remote:        node-pre-gyp ERR! node -v v6.9.1
remote:        node-pre-gyp ERR! node-pre-gyp -v v0.6.32
remote:        node-pre-gyp ERR! not ok
remote:        Failed to execute '/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.heroku/node/bin/node /tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --fallback-to-build --module=/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/release/linux_x64/node_openalpr.node --module_name=node_openalpr --module_path=/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/node_modules/node-openalpr/release/linux_x64' (1)
remote:        npm ERR! Linux 3.13.0-105-generic
remote:        npm ERR! argv "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.heroku/node/bin/node" "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_4dd15daf9538fffbff730d89a3bebbbd/.npmrc"
remote:        npm ERR! node v6.9.1
remote:        npm ERR! npm  v3.10.8
remote:        npm ERR! code ELIFECYCLE
remote:        
remote:        npm ERR! node-openalpr@1.1.1 install: `node-pre-gyp install --build-from-source --fallback-to-build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the node-openalpr@1.1.1 install script 'node-pre-gyp install --build-from-source --fallback-to-build'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the node-openalpr package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-pre-gyp install --build-from-source --fallback-to-build
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs node-openalpr
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls node-openalpr
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_4dd15daf9538fffbff730d89a3bebbbd/npm-debug.log
remote: 
remote: -----> Build failed

```

I have tried `brew uninstall openalpr` and `brew install openalpr` and then `npm install node-openalpr` but still getting the same error. 
Don't know if it is necessary to say, I brew install alpr from my app root directory.

Any idea ?

**Comment by dustinblanchard** [comment]
@devhaoy any luck with this? I haven't figured out how to get the openalpr binaries to install on heroku.
