### ISSUE TITLE
Error: node-openalpr package.json is not node-pre-gyp ready:

### ISSUE THREAD

**Issue by AviFix** [netPark/node-openalpr#27]
Hi

i install openalpr and when i try to npm install node-openalpr this error happens

`node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: node-openalpr package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack at validate_config (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack at Object.module.exports.evaluate (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack at handle_gyp_opts (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:59:27)
node-pre-gyp ERR! stack at configure (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/configure.js:12:5)
node-pre-gyp ERR! stack at /home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/build.js:43:13
node-pre-gyp ERR! stack at ChildProcess. (/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.13.0-37-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr/node_modules/.bin/node-pre-gyp" "install" "--build-from-source" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/Escritorio/Watson/Watsi/node_modules/node-openalpr
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! This is a bug in node-pre-gyp.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR! https://github.com/mapbox/node-pre-gyp/issues
npm WARN watsi@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-openalpr@1.1.1 install: node-pre-gyp install --build-from-source --fallback-to-build
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-openalpr@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ubuntu/.npm/_logs/2018-03-23T19_32_29_952Z-debug.log`

This is the solution: https://github.com/openalpr/openalpr/issues/643#issuecomment-392371777

If you could please update your ripo

Thanks

**Comment by anshgupta1234** [comment]
+1

**Comment by HighSoftWare96** [comment]
https://github.com/openalpr/openalpr/issues/643

**Comment by gbertoncelli** [comment]
Simply change the package.json binary.host to this repo url. Doing MR.
